import { defineCollection, z } from "astro:content";
import { cookbookDocsLoader } from "./loaders/cookbook-docs-loader";

export const collections = {
	// `cookbookDocsLoader()` loads the docs tree via glob() AND injects one entry
	// per example README (id `cookbooks/<slug>`) through Astro's content layer, so
	// cookbook pages are auto-generated by Astro — no prebuild compile step. Routes
	// are derived from each entry id by src/pages/[...slug].astro.
	docs: defineCollection({
		loader: cookbookDocsLoader(),
		schema: z
			.object({
				title: z.string(),
				description: z.string().optional(),
			})
			.passthrough(),
	}),
};
