export type {
	AgentOsCreateSidecarOptions,
	AgentOsLimits,
	AgentOsOptions,
	AgentOsSharedSidecarOptions,
	AgentOsSidecarConfig,
	AgentOsSidecarDescription,
	AgentExitEvent,
	AgentExitHandler,
	AgentRestartOutcome,
	AgentStderrEvent,
	AgentStderrHandler,
	AgentRegistryEntry,
	BatchReadResult,
	BatchWriteEntry,
	BatchWriteResult,
	DirEntry,
	DynamicMountDescriptor,
	ExportRootFilesystemOptions,
	HttpRequest,
	HttpResponse,
	LimitWarning,
	LimitWarningHandler,
	MountConfig,
	MountInfo,
	MountConfigJsonObject,
	MountConfigJsonPrimitive,
	MountConfigJsonValue,
	NativeMountConfig,
	NativeMountPluginDescriptor,
	NativeRootFilesystemConfig,
	OverlayMountConfig,
	OverlayRootFilesystemConfig,
	PlainMountConfig,
	ProcessTreeNode,
	ProcessExit,
	ProcessOutput,
	ReaddirEntry,
	ReaddirRecursiveOptions,
	RootFilesystemConfig,
	RootLowerInput,
	SpawnedProcessInfo,
	SpawnOptions,
	ShellData,
	ShellExit,
	ShellOptions,
} from "./agent-os.js";
export type * from "./session-api.js";
/**
 * An agent type id — the `name` of an `/opt/agentos` agent package manifest
 * (e.g. `"pi"`, `"claude"`). Agents are resolved by the SIDECAR from the projected
 * package manifest (`/opt/agentos/<name>/current/agentos-package.json`); the client
 * passes only the name, so any manifest `name` is a valid agent type.
 */
export type AgentType = string;
export type {
	CronAction,
	CronActionInfo,
	CronEvent,
	CronEventHandler,
	CronJob,
	CronJobInfo,
	CronJobOptions,
	ScheduleDriver,
	ScheduleEntry,
	ScheduleHandle,
} from "./cron/index.js";
export type {
	HostDirBackendOptions,
	HostDirMountPluginConfig,
	NodeModulesMountConfig,
} from "./host-dir-mount.js";
export type { Binding, BindingExample, Bindings } from "./bindings.js";
export type {
	FilesystemSnapshotExport,
	LayerHandle,
	LayerStore,
	OverlayFilesystemMode,
	RootSnapshotExport,
	SnapshotImportSource,
	SnapshotLayerHandle,
	WritableLayerHandle,
} from "./layers.js";
export type { SoftwareInput, SoftwareRoot } from "./packages.js";
export type {
	AgentBlock,
	PackageDescriptor,
	PackageRef,
	SoftwarePackageRef,
} from "./agentos-package.js";
export type {
	ChildProcessPermissions,
	ConnectTerminalOptions,
	EnvPermissions,
	ExecOptions,
	ExecResult,
	FsPermissionRule,
	FsPermissions,
	KernelExecOptions,
	KernelExecResult,
	KernelSpawnOptions,
	NetworkAccessRequest,
	NetworkPermissions,
	OpenShellOptions,
	PatternPermissionRule,
	PermissionDecision,
	PermissionMode,
	Permissions,
	ProcessInfo,
	RulePermissions,
	StdioChannel,
	TimingMitigation,
	VirtualDirEntry,
	VirtualFileSystem,
	VirtualStat,
} from "./runtime.js";
